#!/usr/bin/env bash

PYTHON_ENV="env_h200-paradigma-inc-vllm-v0260"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV="env VLLM_PLUGINS=limite"
MODEL_REPO="paradigma-inc/limite-1b-violetto"
MODEL_NAME="limite"
SERVED_MODEL_NAME="limite-1b-violetto"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser deepseek_r1"
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER=""
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS=""

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90="--attention-backend FLASH_ATTN"
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=131072
GPU_MEM_UTIL_VALUE_SM90=0.86
TENSOR_PARALLEL_SIZE_SM90=1

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=131072
GPU_MEM_UTIL_VALUE_SM100=0
TENSOR_PARALLEL_SIZE_SM100=1

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=131072
GPU_MEM_UTIL_VALUE_SM103=0
TENSOR_PARALLEL_SIZE_SM103=1

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=131072
GPU_MEM_UTIL_VALUE_SM120=0
TENSOR_PARALLEL_SIZE_SM120=1

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=131072
GPU_MEM_UTIL_VALUE_SM121=0
TENSOR_PARALLEL_SIZE_SM121=1

run_inference_recipe "$@"
