#!/usr/bin/env bash

PYTHON_ENV="env_h200-ibm-vllm"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV=""
MODEL_REPO="ibm-granite/granite-4.2-8b"
MODEL_NAME="granite"
SERVED_MODEL_NAME="granite-4.2-8b"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser granite_thinking_parser"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser qwen3_coder"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=1
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE="--no-enable-prefix-caching"
REASONING_PARSER_PLUGIN="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/plugin/granite_thinking_parser.py"
EXTRA_ARGS="--dtype bfloat16"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90=""
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=131072
GPU_MEM_UTIL_VALUE_SM90=0.864805
TENSOR_PARALLEL_SIZE_SM90=1

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=131072
GPU_MEM_UTIL_VALUE_SM120="0"
TENSOR_PARALLEL_SIZE_SM120=1

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
