#!/usr/bin/env bash

PYTHON_ENV="env_h200-glm53-vllm-v0290"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV="env FLASH_ATTENTION_CUTE_DSL_CACHE_ENABLED=1 VLLM_ENGINE_READY_TIMEOUT_S=3600"
MODEL_REPO="stepfun-ai/Step-3.5-Flash"
MODEL_NAME="step3p5"
SERVED_MODEL_NAME="stepfun-ai/Step-3.5-Flash"
TRUST_REMOTE_CODE="--trust-remote-code"
REASONING_PARSER="--reasoning-parser $MODEL_NAME"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser $MODEL_NAME"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--enable-expert-parallel --disable-cascade-attn"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90=""
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=262144
GPU_MEM_UTIL_VALUE_SM90=0.85
TENSOR_PARALLEL_SIZE_SM90=4

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=262144
GPU_MEM_UTIL_VALUE_SM120="0"
TENSOR_PARALLEL_SIZE_SM120=4

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
