#!/usr/bin/env bash

PYTHON_ENV="env_h200-cohere-vllm-pr-54479"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV=""
MODEL_REPO="CohereLabs/command-a-plus-05-2026-bf16"
MODEL_NAME="cohere_command4"
SERVED_MODEL_NAME="command-a-plus"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser $MODEL_NAME"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser $MODEL_NAME"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--dtype bfloat16"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90=""
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=200000
GPU_MEM_UTIL_VALUE_SM90=0.877427
TENSOR_PARALLEL_SIZE_SM90=4

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=200000
GPU_MEM_UTIL_VALUE_SM120="0"
TENSOR_PARALLEL_SIZE_SM120=4

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
