#!/usr/bin/env bash

PYTHON_ENV=""
INFERENCE_PROVIDER=""
INFERENCE_ENV=""
MODEL_REPO=""
MODEL_NAME=""
SERVED_MODEL_NAME=""
TRUST_REMOTE_CODE=""
REASONING_PARSER=""
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER=""
METRICS_FLAG=""
HOST=""
DEFAULT_PORT=
API_KEY=""

ENABLE_CACHE_FLAG=
ENABLE_SPECULATIVE=
ENABLE_REASONING_PARSER=
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS=""

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90=""
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=
GPU_MEM_UTIL_VALUE_SM90=
TENSOR_PARALLEL_SIZE_SM90=

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=
GPU_MEM_UTIL_VALUE_SM120=""
TENSOR_PARALLEL_SIZE_SM120=

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
