#!/usr/bin/env bash

PYTHON_ENV="env_h200-nvidia-muse-sglang-v0520"
INFERENCE_PROVIDER="SGLang"
INFERENCE_ENV=""
MODEL_REPO="nvidia/Muse-Glimmer-30B-NVFP4"
MODEL_NAME="muse"
SERVED_MODEL_NAME="muse-glimmer-nvfp4"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser muse"
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER="--tool-call-parser muse"
METRICS_FLAG="--enable-metrics"
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=1
ENABLE_REASONING_PARSER=0
SPECULATIVE="--speculative-algorithm DFLASH --speculative-draft-model-path meta-models/Muse-Glimmer-30B-assistant --speculative-draft-model-quantization fp8"
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--kv-cache-dtype fp8_e4m3"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90="--attention-backend fa3"
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90=""
CONTEXT_LEN_VALUE_SM90=131072
GPU_MEM_UTIL_VALUE_SM90=0.84
TENSOR_PARALLEL_SIZE_SM90=1

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=131072
GPU_MEM_UTIL_VALUE_SM100=0
TENSOR_PARALLEL_SIZE_SM100=1

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=131072
GPU_MEM_UTIL_VALUE_SM103=0
TENSOR_PARALLEL_SIZE_SM103=1

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=131072
GPU_MEM_UTIL_VALUE_SM120=0
TENSOR_PARALLEL_SIZE_SM120=1

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=131072
GPU_MEM_UTIL_VALUE_SM121=0
TENSOR_PARALLEL_SIZE_SM121=1

run_inference_recipe "$@"
