#!/usr/bin/env bash

PYTHON_ENV="env_xiaomimimo-flash-vllm-1ea7c63"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV=""
MODEL_REPO="${MIMO_MODEL_PATH:?Set MIMO_MODEL_PATH to the complete local XiaomiMiMo/MiMo-V2.6-Flash-RL checkpoint}"
MODEL_NAME="mimo_v2"
SERVED_MODEL_NAME="mimo-v2.6-flash-rl"
TRUST_REMOTE_CODE="--trust-remote-code"
REASONING_PARSER="--reasoning-parser mimo"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser mimo"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--generation-config vllm"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90="--attention-backend FLASH_ATTN_DIFFKV"
BACKEND_FP8_GEMM_SM90="--linear-backend flashinfer_cutlass"
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90="--moe-backend marlin"
CONTEXT_LEN_VALUE_SM90=1048576
GPU_MEM_UTIL_VALUE_SM90=0.88
TENSOR_PARALLEL_SIZE_SM90=2

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=1048576
GPU_MEM_UTIL_VALUE_SM100=0
TENSOR_PARALLEL_SIZE_SM100=2

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=1048576
GPU_MEM_UTIL_VALUE_SM103=0
TENSOR_PARALLEL_SIZE_SM103=2

BACKEND_ATTENTION_SM120="--attention-backend TRITON_ATTN_DIFFKV"
BACKEND_FP8_GEMM_SM120="--linear-backend deep_gemm"
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120="--moe-backend deep_gemm"
CONTEXT_LEN_VALUE_SM120=1048576
GPU_MEM_UTIL_VALUE_SM120="0.83"
TENSOR_PARALLEL_SIZE_SM120=4

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=1048576
GPU_MEM_UTIL_VALUE_SM121=0
TENSOR_PARALLEL_SIZE_SM121=2

run_inference_recipe "$@"
