#!/usr/bin/env bash

PYTHON_ENV="env_rtxpro6k-nvidia-glm53flash-sglang-pr-38430"
INFERENCE_PROVIDER="SGLang"
INFERENCE_ENV=""
MODEL_REPO="nvidia/GLM-5.3-Flash-NVFP4"
MODEL_NAME="glm5next"
SERVED_MODEL_NAME="nvidia/GLM-5.3-Flash-NVFP4"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser glm45"
ENABLE_AUTO_TOOL_CHOICE=""
TOOL_CALL_PARSER="--tool-call-parser glm47"
METRICS_FLAG="--enable-metrics"
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION="--quantization modelopt_fp4"
NO_PREFIX_CACHE=""
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS=""

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90=""
BACKEND_FP8_GEMM_SM90=""
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90="--moe-runner-backend marlin"
CONTEXT_LEN_VALUE_SM90=1048576
GPU_MEM_UTIL_VALUE_SM90=0.85
TENSOR_PARALLEL_SIZE_SM90=4

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120="--attention-backend dsa --dsa-prefill-backend flashinfer_sparse_mla --dsa-decode-backend flashinfer_sparse_mla"
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120="--fp4-gemm-backend flashinfer_cutlass"
BACKEND_MOE_RUNNER_SM120="--moe-runner-backend flashinfer_cutlass"
CONTEXT_LEN_VALUE_SM120=1048576
GPU_MEM_UTIL_VALUE_SM120="0.77"
TENSOR_PARALLEL_SIZE_SM120=4

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
