#!/usr/bin/env bash

PYTHON_ENV="env_rtxpro6k-deepseek-v41-vllm-pr-56509"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV="env VLLM_ENGINE_READY_TIMEOUT_S=3600"
MODEL_REPO="nvidia/DeepSeek-V4.1-Flash-NVFP4"
MODEL_NAME="deepseek_v41"
SERVED_MODEL_NAME="nvidia/DeepSeek-V4.1-Flash-NVFP4"
TRUST_REMOTE_CODE=""
REASONING_PARSER="--reasoning-parser deepseek_v41"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser deepseek_v41"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=1
ENABLE_SPECULATIVE=0
ENABLE_REASONING_PARSER=0
SPECULATIVE=""
QUANTIZATION=""
NO_PREFIX_CACHE="--no-enable-prefix-caching"
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--tokenizer-mode deepseek_v41 --mm-encoder-tp-mode data --engram-config {\"cpu_offload\":false} --enable-chunked-prefill --model-loader-extra-config {\"enable_multithread_load\":true,\"num_threads\":128}"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90="--attention-backend FLASHMLA_SPARSE_DSV41"
BACKEND_FP8_GEMM_SM90="--linear-backend marlin"
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90="--moe-backend marlin"
CONTEXT_LEN_VALUE_SM90=1048576
GPU_MEM_UTIL_VALUE_SM90=0.88
TENSOR_PARALLEL_SIZE_SM90=8

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120="--attention-backend FLASHINFER_MLA_SPARSE_DSV41"
BACKEND_FP8_GEMM_SM120="--linear-backend flashinfer_cutlass"
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120="--moe-backend b12x"
CONTEXT_LEN_VALUE_SM120=262144
GPU_MEM_UTIL_VALUE_SM120="0.83"
TENSOR_PARALLEL_SIZE_SM120=8

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
