#!/usr/bin/env bash

PYTHON_ENV="env_xiaomimimo-flash-vllm-1ea7c63"
INFERENCE_PROVIDER="vLLM"
INFERENCE_ENV=""
MODEL_REPO="${HF_HOME:-$HOME/.cache/huggingface}/mimo-v2.6-pro-rl"
MODEL_NAME="mimo_v2"
SERVED_MODEL_NAME="mimo-v2.6-pro-rl"
TRUST_REMOTE_CODE="--trust-remote-code"
REASONING_PARSER="--reasoning-parser mimo"
ENABLE_AUTO_TOOL_CHOICE="--enable-auto-tool-choice"
TOOL_CALL_PARSER="--tool-call-parser mimo"
METRICS_FLAG=""
HOST="0.0.0.0"
DEFAULT_PORT=8000
API_KEY="--api-key YOUR_API_KEY"

ENABLE_CACHE_FLAG=0
ENABLE_SPECULATIVE=1
ENABLE_REASONING_PARSER=0
SPECULATIVE="--speculative-config {\"method\":\"dflash\",\"model\":\"${HF_HOME:-$HOME/.cache/huggingface}/mimo-v2.6-pro-rl/dflash\",\"num_speculative_tokens\":7}"
QUANTIZATION=""
NO_PREFIX_CACHE="--no-enable-prefix-caching"
REASONING_PARSER_PLUGIN=""
EXTRA_ARGS="--generation-config vllm"

RECIPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$RECIPE_DIR/../../tools/recipes/inference_recipe.sh"

BACKEND_ATTENTION_SM90="--attention-backend FLASH_ATTN_DIFFKV"
BACKEND_FP8_GEMM_SM90="--linear-backend flashinfer_cutlass"
BACKEND_FP4_GEMM_SM90=""
BACKEND_MOE_RUNNER_SM90="--moe-backend marlin"
CONTEXT_LEN_VALUE_SM90=1048576
GPU_MEM_UTIL_VALUE_SM90=0.85
TENSOR_PARALLEL_SIZE_SM90=8

BACKEND_ATTENTION_SM100=""
BACKEND_FP8_GEMM_SM100=""
BACKEND_FP4_GEMM_SM100=""
BACKEND_MOE_RUNNER_SM100=""
CONTEXT_LEN_VALUE_SM100=""
GPU_MEM_UTIL_VALUE_SM100=""
TENSOR_PARALLEL_SIZE_SM100=""

BACKEND_ATTENTION_SM103=""
BACKEND_FP8_GEMM_SM103=""
BACKEND_FP4_GEMM_SM103=""
BACKEND_MOE_RUNNER_SM103=""
CONTEXT_LEN_VALUE_SM103=""
GPU_MEM_UTIL_VALUE_SM103=""
TENSOR_PARALLEL_SIZE_SM103=""

BACKEND_ATTENTION_SM120=""
BACKEND_FP8_GEMM_SM120=""
BACKEND_FP4_GEMM_SM120=""
BACKEND_MOE_RUNNER_SM120=""
CONTEXT_LEN_VALUE_SM120=""
GPU_MEM_UTIL_VALUE_SM120="-1"
TENSOR_PARALLEL_SIZE_SM120=

BACKEND_ATTENTION_SM121=""
BACKEND_FP8_GEMM_SM121=""
BACKEND_FP4_GEMM_SM121=""
BACKEND_MOE_RUNNER_SM121=""
CONTEXT_LEN_VALUE_SM121=""
GPU_MEM_UTIL_VALUE_SM121=""
TENSOR_PARALLEL_SIZE_SM121=""

run_inference_recipe "$@"
